### ISSUE TITLE
Английскую версию бы :)

### ISSUE THREAD

**Issue by illus0r** [algenon/whatbrowser#3]
![image](https://cloud.githubusercontent.com/assets/797993/20558860/4575dd4a-b183-11e6-94e4-58c0ba0a30a4.png)

Проект клёвый, спасибо.
Жалко, коллеги мои боятся кириллицы и пользоваться русскими сайтами не умеют.

**Comment by algenon** [comment]
Тогда им прямая дорога сюда: [whatsmybrowser.org](http://www.whatsmybrowser.org/)

**Comment by illus0r** [comment]
@algenon, спасибо!
